version: "3"

services:
  main-db:
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=postrgres
      - POSTGRES_PASSWORD=postrgres
      - POSTGRES_DB=postrgres
    volumes:
      - main-db:/var/lib/postgresql/data
volumes:
  main-db: 